name: build docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cp .devcontainer/Dockerfile .
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
